### ISSUE TITLE
where to find the source of deb packages published here?

### ISSUE THREAD

**Issue by picospuch** [Seeed-Studio/seeed-linux-deb#1]
Hi, I'm a fan of seeed odyssey npi board. I'm curious about the source code of the deb packages especially the 'linux-upstream' kernel packages and want to learn kernel driver development using the npi board.

The wiki [https://wiki.seeedstudio.com/ODYSSEY-STM32MP157C/](https://wiki.seeedstudio.com/ODYSSEY-STM32MP157C/) also only provides the whole system image but no modified kernel source. The articles about "advance linux development" in the wiki lead me to build a kernel bootable but only with functional uart.

Learners and hackers who want to rebuild the kernel or even upgrade it to v5.x.x with ALL peripherals functional will be happier with this great open-hardware board and your help.

**Comment by Pillar1989** [comment]
@leadercxn  please help this users

**Comment by leadercxn** [comment]
> Hi, I'm a fan of seeed odyssey npi board. I'm curious about the source code of the deb packages especially the 'linux-upstream' kernel packages and want to learn kernel driver development using the npi board.
> 
> The wiki https://wiki.seeedstudio.com/ODYSSEY-STM32MP157C/ also only provides the whole system image but no modified kernel source. The articles about "advance linux development" in the wiki lead me to build a kernel bootable but only with functional uart.
> 
> Learners and hackers who want to rebuild the kernel or even upgrade it to v5.x.x with ALL peripherals functional will be happier with this great open-hardware board and your help.



> Hi, I'm a fan of seeed odyssey npi board. I'm curious about the source code of the deb packages especially the 'linux-upstream' kernel packages and want to learn kernel driver development using the npi board.
> 
> The wiki https://wiki.seeedstudio.com/ODYSSEY-STM32MP157C/ also only provides the whole system image but no modified kernel source. The articles about "advance linux development" in the wiki lead me to build a kernel bootable but only with functional uart.
> 
> Learners and hackers who want to rebuild the kernel or even upgrade it to v5.x.x with ALL peripherals functional will be happier with this great open-hardware board and your help.

@picospuch  Hi,
Like ODYSSEY-STM32MP157C, you can see this file "/etc/apt/sources.list" in system, apt-get command is according to this file. You can find there
```sh
deb [arch=armhf] https://seeed-studio.github.io/seeed-linux-deb/ buster main
#deb-src [arch=armhf] https://seeed-studio.github.io/seeed-linux-deb/ buster main
```
in ODYSSEY-STM32MP157C  /etc/apt/sources.list, it points to our Github server.

And how to create and publish personal deb packages, please refer to this link
[Aptly](https://www.aptly.info/doc/aptly/publish/repo/)
When you have published your  .deb packages , you can push them to your github pages. Please refer to this link.
[Github Pages](https://jekyllrb.com/docs/github-pages/)

I hope i can solve your problems. 
THANKS~

**Comment by picospuch** [comment]
Thank you @leadercxn you solved my issue. For help to others, Listing source tree here:
- linux https://github.com/Seeed-Studio/linux/tree/stm32-4.19.y
- u-boot https://github.com/Seeed-Studio/u-boot/tree/v2018.11-stm32mp-s
